### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Crizz0** [Crizz0/whoposted#1]
Before this extension finally will work:
- [ ] Create good output -> JS popup
- [x] Show link on reply count only to users not guest
- [ ] Don't show the link to topics with no replies
- [ ] Clean up the code
- [ ] Test the ext in big topics

**Comment by Crizz0** [comment]
TODO Notice:
Give link a "whoposted=topic_id". The link calls the controller/AJAX callback calls the function in controller. 

PHP gives content to variables and callback to AJAX (see core.js). 

JS opens popup --> table 

without JS opens new window -> table
